/* tslint:disable */
/* eslint-disable */
/**
 * FizzBuzzService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface GameStorage
 */
export interface GameStorage {
    /**
     * 
     * @type {string}
     * @memberof GameStorage
     */
    gameCode?: string;
    /**
     * 
     * @type {string}
     * @memberof GameStorage
     */
    game?: string;
    /**
     * 
     * @type {number}
     * @memberof GameStorage
     */
    created?: number;
    /**
     * 
     * @type {number}
     * @memberof GameStorage
     */
    modified?: number;
}

/**
 * Check if a given object implements the GameStorage interface.
 */
export function instanceOfGameStorage(value: object): value is GameStorage {
    return true;
}

export function GameStorageFromJSON(json: any): GameStorage {
    return GameStorageFromJSONTyped(json, false);
}

export function GameStorageFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameStorage {
    if (json == null) {
        return json;
    }
    return {
        
        'gameCode': json['gameCode'] == null ? undefined : json['gameCode'],
        'game': json['game'] == null ? undefined : json['game'],
        'created': json['created'] == null ? undefined : json['created'],
        'modified': json['modified'] == null ? undefined : json['modified'],
    };
}

export function GameStorageToJSON(json: any): GameStorage {
    return GameStorageToJSONTyped(json, false);
}

export function GameStorageToJSONTyped(value?: GameStorage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'gameCode': value['gameCode'],
        'game': value['game'],
        'created': value['created'],
        'modified': value['modified'],
    };
}

